import Head from "next/head";
import { Search } from "../components";

export default function Characters() {
  return (
    <>
      <Head>
        <title>RAM APP</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Search />
    </>
  );
}
